export const lendingPoolAbi = [
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tierIndex", type: "uint8" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tierIndex", type: "uint8" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claimRewards",
    stateMutability: "nonpayable",
    inputs: [{ name: "tierIndex", type: "uint8" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claimLoan",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "att",
        type: "tuple",
        components: [
          { name: "borrower", type: "address" },
          { name: "tierIndex", type: "uint8" },
          { name: "nftContract", type: "address" },
          { name: "tokenId", type: "uint256" },
          { name: "sepoliaDepositId", type: "bytes32" },
          { name: "nonce", type: "uint256" },
          { name: "expiry", type: "uint256" },
        ],
      },
      { name: "signature", type: "bytes" },
    ],
    outputs: [{ name: "loanId", type: "uint256" }],
  },
  {
    type: "function",
    name: "repayLoan",
    stateMutability: "nonpayable",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "markDefault",
    stateMutability: "nonpayable",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "pendingRewards",
    stateMutability: "view",
    inputs: [
      { name: "tierIndex", type: "uint8" },
      { name: "lender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "idleLiquidity",
    stateMutability: "view",
    inputs: [{ name: "tierIndex", type: "uint8" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "tierAmount",
    stateMutability: "view",
    inputs: [{ name: "tierIndex", type: "uint8" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "dailyRewardRate",
    stateMutability: "view",
    inputs: [{ name: "tierIndex", type: "uint8" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "pools",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint8" }],
    outputs: [
      { name: "totalDeposits", type: "uint256" },
      { name: "totalOutstanding", type: "uint256" },
      { name: "activeLoanCount", type: "uint256" },
      { name: "accRewardPerShare", type: "uint256" },
      { name: "lastUpdateTs", type: "uint256" },
      { name: "treasury", type: "address" },
    ],
  },
  {
    type: "function",
    name: "lenderInfo",
    stateMutability: "view",
    inputs: [
      { name: "", type: "uint8" },
      { name: "", type: "address" },
    ],
    outputs: [
      { name: "deposited", type: "uint256" },
      { name: "rewardDebt", type: "uint256" },
      { name: "pendingRewards", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "loans",
    stateMutability: "view",
    inputs: [{ name: "loanId", type: "uint256" }],
    outputs: [
      { name: "borrower", type: "address" },
      { name: "tierIndex", type: "uint8" },
      { name: "principal", type: "uint256" },
      { name: "startTs", type: "uint256" },
      { name: "dueTs", type: "uint256" },
      { name: "nftContract", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "sepoliaDepositId", type: "bytes32" },
      { name: "active", type: "bool" },
      { name: "repaid", type: "bool" },
      { name: "defaulted", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "activeLoanOf",
    stateMutability: "view",
    inputs: [{ name: "borrower", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "blacklisted",
    stateMutability: "view",
    inputs: [{ name: "borrower", type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "usdc",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "rewardToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "event",
    name: "LoanClaimed",
    inputs: [
      { name: "loanId", type: "uint256", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "tierIndex", type: "uint8", indexed: true },
      { name: "principal", type: "uint256", indexed: false },
      { name: "upfrontInterest", type: "uint256", indexed: false },
      { name: "dueTs", type: "uint256", indexed: false },
      { name: "sepoliaDepositId", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "LoanRepaid",
    inputs: [
      { name: "loanId", type: "uint256", indexed: true },
      { name: "borrower", type: "address", indexed: true },
    ],
  },
] as const;
